defaults:
  - base_dataset
  - view_sampler: bounded

name: shoes
roots: [/mnt/c/Users/lukas/shoe_renders_final]

input_image_shape: [224, 224]
original_image_shape: [512, 512]
cameras_are_circular: false

view_sampler:
  num_context_views: 2
  num_target_views: 3
  max_img_per_gpu: 8
