defaults:
  - base_dataset
  - view_sampler: shoes_geometry

name: shoes
roots: [/mnt/c/Users/lukas/shoe_renders_final]

input_image_shape: [224, 224]
original_image_shape: [512, 512]
cameras_are_circular: false
train_background_mode: random
eval_background_mode: white

view_sampler:
  num_context_views: 2
  num_target_views: 1
  max_img_per_gpu: 8
